version: '2'

volumes:
  postgres_data: {}
  backend_mediafiles: {}

services:
  postgres:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file: .env

  backend:
    build:
      context: .
    volumes:
      - ./staticfiles:/staticfiles/
      - backend_mediafiles:/mediafiles/
    command: /start_prod.sh
    entrypoint: /entrypoint.sh
    restart: always
    env_file: .env
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./staticfiles:/staticfiles/
      - backend_mediafiles:/mediafiles/
    restart: always
    depends_on:
      - backend