version: '2'

volumes:
  redis_data: {}

services:
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always

  server:
    build: .
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    depends_on:
      - redis